### ISSUE TITLE
put for /dogs/:id

### ISSUE THREAD

**Issue by mhtien** [oliverjam/learn-rest-apis#5]
I'm not sure if its just me..  but under Protecting routes there is mention of a PUT /dogs/:id and I don't think this route and handler is mentioned before this?

When do we create this?

**Comment by oliverjam** [comment]
Oh sorry 🤦 There used to be an extra "add a PUT" step, but the workshop was way too long so I removed it (since it's effectively the same as the POST one). I guess I missed one of the references to it
